//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelativeStrengthCalculator.SchwartzMalone.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RelativeStrengthCalculator.SchwartzMalone.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40,1.1938
        ///40.1,1.1915
        ///40.2,1.1892
        ///40.3,1.1869
        ///40.4,1.1846
        ///40.5,1.1823
        ///40.6,1.1801
        ///40.7,1.1778
        ///40.8,1.1756
        ///40.9,1.1733
        ///41,1.1711
        ///41.1,1.1689
        ///41.2,1.1667
        ///41.3,1.1645
        ///41.4,1.1623
        ///41.5,1.1601
        ///41.6,1.1579
        ///41.7,1.1557
        ///41.8,1.1535
        ///41.9,1.1514
        ///42,1.1492
        ///42.1,1.1471
        ///42.2,1.1452
        ///42.3,1.1428
        ///42.4,1.1407
        ///42.5,1.1386
        ///42.6,1.1365
        ///42.7,1.1344
        ///42.8,1.1323
        ///42.9,1.1303
        ///43,1.1282
        ///43.1,1.1261
        ///43.2,1.1241
        ///43.3,1.1221
        ///43.4,1.1201
        ///43.5,1.1182
        ///43.6,1.1159
        ///43.7,1.1139
        ///43.8,1.1119
        ///43.9,1.1099
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MaloneCoefficients {
            get {
                return ResourceManager.GetString("MaloneCoefficients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40,1.3133
        ///40.1,1.3092
        ///40.2,1.3052
        ///40.3,1.3011
        ///40.4,1.2971
        ///40.5,1.2931
        ///40.6,1.2891
        ///40.7,1.2851
        ///40.8,1.2812
        ///40.9,1.2773
        ///41,1.2734
        ///41.1,1.2695
        ///41.2,1.2656
        ///41.3,1.2618
        ///41.4,1.258
        ///41.5,1.2542
        ///41.6,1.2504
        ///41.7,1.2467
        ///41.8,1.2429
        ///41.9,1.2392
        ///42,1.2355
        ///42.1,1.2318
        ///42.2,1.2282
        ///42.3,1.2245
        ///42.4,1.2209
        ///42.5,1.2173
        ///42.6,1.2138
        ///42.7,1.2102
        ///42.8,1.2067
        ///42.9,1.2032
        ///43,1.1997
        ///43.1,1.1962
        ///43.2,1.1927
        ///43.3,1.1893
        ///43.4,1.1858
        ///43.5,1.1824
        ///43.6,1.1791
        ///43.7,1.1757
        ///43.8,1.1723
        ///43.9,1.169
        ///44 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SwartzCoefficients {
            get {
                return ResourceManager.GetString("SwartzCoefficients", resourceCulture);
            }
        }
    }
}
